name: Publish package to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: Maven site
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: '[{ "id": "github", "password": "${{ secrets.MAVEN_GITHUB_TOKEN }}" }]'
      - name: Publish package
        run: ./mvnw clean compile deploy site

